---
- name: Prepare the testing machine for running Mock tests
  hosts: all
  user: "root"
  vars:
    mock_test_username: mockbuild
    mock_test_workdir: /home/mock/mock-testing
    mock_gpg_dir: "/home/mockbuild/gpg"
    mock_gpg_wrapper: "/home/mockbuild/gpg-mock"
    mock_test_rpmmacros: /home/mockbuild/.rpmmacros
    mock_lvm_volume: /test-lvm-disk
    mock_clone: /home/mockbuild/mock
    no_subscription_management: true

  tasks:
    - include_tasks: tasks/main.yml

    - name: upload the "install copr package" script
      copy:
        src: "{{ item }}"
        dest: "/usr/bin/{{ item }}"
        mode: '0755'
      loop:
        - install-copr-packages
        - install-mock-packages-built-by-packit
