.TH "mock-parse-buildlog" "1" "@VERSION@" "Silvie Chlupova"
.SH NAME
mock-parse-buildlog \- parse build.log
.SH SYNOPSIS
.B mock-parse-buildlog
\fB\-\-path\fR \fIPATH\fR
.SH DESCRIPTION
.B mock-parse-buildlog
parses a build.log file saved in logs directory and tries to recognize what caused that a build failed and prints to stdout the cause.
.SH OPTIONS
.TP
\fB\-p\fR PATH, \fB\-\-path\fR \fIPATH\fR
set the path where is build.log located.

.SH "AUTHORS"
Silvie Chlupova
