#! /bin/bash

# Helper script to update CI scripting on Copr side

script=$(readlink -f "$(dirname "$0")")/copr-custom-script

workdir=$(dirname "$script")

PROJECT_PR=@mock/mock-pull-requests-el7
PROJECT_PUSH=@mock/mock-el7

build_deps=(
    bsdtar
    tito
)

copr_cmd=(
    copr edit-package-custom \
        --webhook-rebuild on \
        --script "$script" \
        --script-chroot "fedora-latest-x86_64" \
        --script-builddeps "${build_deps[*]}"
)

"${copr_cmd[@]}" "$PROJECT_PR"   --name mock               --script-resultdir results/mock              --max-builds 15
"${copr_cmd[@]}" "$PROJECT_PR"   --name mock-core-configs  --script-resultdir results/mock-core-configs --max-builds 15
"${copr_cmd[@]}" "$PROJECT_PUSH" --name mock               --script-resultdir results/mock
"${copr_cmd[@]}" "$PROJECT_PUSH" --name mock-core-configs  --script-resultdir results/mock-core-configs
