/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Location of libraries */
#define LIBDIR "/usr/lib"

/* Location of local state files */
#define LOCALSTATEDIR "/var"

/* Define the version */
#define MOCK "0.1"

/* Name of package */
#define PACKAGE "mock"

/* Location of mock roots */
#define ROOTSDIR "/var/lib/mock"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Location of configuration files */
#define SYSCONFDIR "/etc"

/* Version number of package */
#define VERSION "0.1"
