---
name: Fedora Copr build

on:
  push:
    branches: [mock-2]
  pull_request:
    branches: [mock-2]
  schedule:
    # This always runs against the default branch.  Two runs per month.
    - cron: '0 0 1,16 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: RPM package
    strategy:
      matrix:
        package:
          - mock
          - mock-core-configs

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1

      - name: Copr build ${{ matrix.package }}
        env:
          COPR_PR_WEBHOOK: https://copr.fedorainfracloud.org/webhooks/custom/53447/3f7fbaf0-1f08-4e49-ad07-1e0941101d3d/${{ matrix.package }}/
          COPR_PUSH_WEBHOOK: ${{ secrets.COPR_PUSH_WEBHOOK_EL7 }}/${{ matrix.package }}/
        run: |
          curl https://raw.githubusercontent.com/praiskup/copr-ci-tooling/main/copr-gh-actions-submit > submit
          bash submit ${{ github.event.pull_request.number }}
