---
name: Lint Shell issues

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  shell-lint-job:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
